### PR TITLE
Pushes the Docker tags we're creating manually 

### PR DESCRIPTION
**Pull request by Beanow**
We didn't explicitly push the new tags we created in our hook.
Meaning only `latest` gets updated as this is part of the orb's command.

See also https://github.com/sourcecred/widgets/pull/22#issuecomment-525861256 and https://github.com/sourcecred/sourcecred/pull/1320#pullrequestreview-281009632

### CODE REVIEW

**Comment by Beanow** [comment]
cc @vsoch does this look right to you?

**Comment by vsoch** [comment]
I might be wrong, but I think you can just `docker push sourcecred/widgets` and all tags will be pushed. The extraneous push for latest won't hurt that much because it would already find the layers. If you want to specifically target the tags to push, then yes, this would work.

**Comment by Beanow** [comment]
Yes I believe you're right. I deliberately chose explicit tags, more out of local workflow habits than anything. Especially on local systems there might be tags created you didn't intend to push and get picked up with this command. Likewise locally having cached of a bazillion tags will slow it down even if they already exist.

For CI, one would expect each workflow run to have a clean docker environment so they should be non-issues.

**Comment by Beanow** [comment]
image
:tada:

**Comment by vsoch** [comment]
Woohoo! My socks have been rocked.

**Pull request merged**
